//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theatre_Nemov_ISP_31
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int id { get; set; }
        public Nullable<int> idActor { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime dateOfStart { get; set; }
        public System.DateTime dateOfEnd { get; set; }
    
        public virtual Actor Actor { get; set; }
    }
}
