//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theatre_Nemov_ISP_31
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spectacle
    {
        public int id { get; set; }
        public string NameOfSpectacle { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public int GenreID { get; set; }
        public int ActorID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
